server:
  port: 8080
spring:
  application:
    name: parking_system
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 阿里的数据库连接池
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/task1?serverTimezone=UTC&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
mybatis-plus:
  configuration:
    cache-enabled: true #开启缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath:/mapper/**/*Mapper.xml